### PR TITLE
Fixing a bug in calculations for Wakeby PDF

### PR DESCRIPTION
**Pull request by bina20**
The calculation of Wakeby PDF was not correct. Used this reference:
https://www.itl.nist.gov/div898/software/dataplot/refman2/auxillar/wakpdf.htm
and R to fix the code and verify the results.

### CODE REVIEW

**Comment by huard** [comment]
Hi @bina20 

I`m not in a position to offer a substantial review, so I'll accept those changes. Thanks for your contribution !

**Review by huard — APPROVED** [review]

**Comment by huard** [comment]
@Zeitsperre I believe this is a breaking change because it changes the number of parameters for the function.

**Comment by Zeitsperre** [comment]
This is True. It seems to modify internal class methods, though (`_*.py`), so it shouldn't change anything on the user end. I don't use lmoments3 enough to know if this is fine.

@aulemahal ?

**Review by aulemahal — CHANGES_REQUESTED** [review]
I'm not sure where the bug in the previous version was.

AFAIU (which is not that much), scipy works with what we could name "normalized" coordinates when dealing with distributions. All distributions have a `loc` and a `scale` parameter. For a given variable X, the implementations must then process $\frac{X - loc}{scale}$. Reading the old and new implementations and skimming through the linked paper I see that one can transform from the old to the paper definition with:

- `scale` -> $\alpha$
- `c` -> $\frac{\gamma}{\alpha}$

Thus the old implementation was equivalent to the Paper*, but the parameter definition was different. By "splitting" $\alpha$ from `scale`, we are introducing an _extra_ parameter, one more than in the paper. This seems strange to me.

* « Equivalent » as long as we restrict `scale > 0` or $\alpha > 0$. I think this is correct, but I'm not sure.

**Pull request closed without merging**
